name: milan
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - geojson
  - progressbar2
  - bokeh
  # - pycountry
  - phonenumbers
  - selenium
  - phantomjs
  - pillow
  - scikit-learn