name: milan
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - geojson
  - progressbar2
  - bokeh
  - phonenumbers
  - selenium
  - phantomjs
  - pillow
  - scikit-learn

